// Generated by Melange

import * as Curry from "melange/lib/es6/curry.mjs";
import * as React from "react";
import * as Caml_option from "melange/lib/es6/caml_option.mjs";

function createStore(initialState, reducer) {
  var state = {
    contents: initialState
  };
  var listeners = {
    contents: []
  };
  var getState = function (param) {
    return state.contents;
  };
  var dispatch = function (action) {
    state.contents = Curry._2(reducer, state.contents, action);
    listeners.contents.forEach(function (listener) {
          Curry._1(listener, undefined);
        });
  };
  var subscribe = function (listener, areEqualOpt, param) {
    var areEqual = areEqualOpt !== undefined ? areEqualOpt : (function (prim0, prim1) {
          return Object.is(prim0, prim1);
        });
    var currentState = {
      contents: state.contents
    };
    var listenerFn = function (param) {
      var state$1 = state.contents;
      if (!Curry._2(areEqual, state$1, currentState.contents)) {
        Curry._1(listener, state$1);
        currentState.contents = state$1;
        return ;
      }
      
    };
    listeners.contents = listeners.contents.concat([listenerFn]);
    return function (param) {
      listeners.contents = listeners.contents.filter(function (l) {
            return l !== listenerFn;
          });
    };
  };
  var subscribeWithSelector = function (selector, listener, areEqualOpt, param) {
    var areEqual = areEqualOpt !== undefined ? areEqualOpt : (function (prim0, prim1) {
          return Object.is(prim0, prim1);
        });
    var currentSlice = {
      contents: Curry._1(selector, state.contents)
    };
    var listenerFn = function (param) {
      var slice = Curry._1(selector, state.contents);
      if (!Curry._2(areEqual, slice, currentSlice.contents)) {
        Curry._1(listener, slice);
        currentSlice.contents = slice;
        return ;
      }
      
    };
    listeners.contents = listeners.contents.concat([listenerFn]);
    return function (param) {
      listeners.contents = listeners.contents.filter(function (l) {
            return l !== listenerFn;
          });
    };
  };
  var useStore = function (areEqual, param) {
    var match = React.useState(function () {
          return 1;
        });
    var forceUpdate = match[1];
    React.useLayoutEffect((function () {
            var unsubscribe = subscribe((function (param) {
                    Curry._1(forceUpdate, (function (x) {
                            return x + 1 | 0;
                          }));
                  }), areEqual, undefined);
            Curry._1(forceUpdate, (function (x) {
                    return x + 1 | 0;
                  }));
            return (function (param) {
                      Curry._1(unsubscribe, undefined);
                    });
          }), []);
    return state.contents;
  };
  var useStoreWithSelector = function (selector, areEqual, param) {
    var sliceRef = React.useRef(undefined);
    var selectorRef = React.useRef(selector);
    var prevSlice = sliceRef.current;
    var prevSelector = selectorRef.current;
    var slice = selector === prevSelector && prevSlice !== undefined ? Caml_option.valFromOption(prevSlice) : Curry._1(selector, state.contents);
    React.useLayoutEffect((function () {
            sliceRef.current = Caml_option.some(slice);
          }), [slice]);
    React.useLayoutEffect((function () {
            selectorRef.current = selector;
          }), [selector]);
    var match = React.useState(function () {
          return 1;
        });
    var forceUpdate = match[1];
    React.useLayoutEffect((function () {
            var unsubscribe = subscribeWithSelector((function (state) {
                    return Curry._1(selectorRef.current, state);
                  }), (function (slice) {
                    sliceRef.current = Caml_option.some(slice);
                    Curry._1(forceUpdate, (function (x) {
                            return x + 1 | 0;
                          }));
                  }), areEqual, undefined);
            sliceRef.current = Caml_option.some(Curry._1(selector, state.contents));
            Curry._1(forceUpdate, (function (x) {
                    return x + 1 | 0;
                  }));
            return (function (param) {
                      Curry._1(unsubscribe, undefined);
                    });
          }), []);
    return slice;
  };
  return {
          getState: getState,
          subscribe: subscribe,
          subscribeWithSelector: subscribeWithSelector,
          dispatch: dispatch,
          useStore: useStore,
          useStoreWithSelector: useStoreWithSelector
        };
}

export {
  createStore ,
}
/* react Not a pure module */
