// Generated by Melange

import * as React from "react";
import * as Belt_List from "melange/lib/es6/belt_List.mjs";
import * as RescriptReactRouter from "@rescript/react/./src/RescriptReactRouter.js";

function NavLink(Props) {
  var to_ = Props.to_;
  var children = Props.children;
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var path;
  if (match) {
    var path$1 = Belt_List.reduce(url.path, "", (function (acc, p) {
            return acc + ("/" + p);
          }));
    var re = new RegExp("/\\/$/g");
    path = path$1.replace(re, "");
  } else {
    path = "/";
  }
  var baseStyle = "focus:outline-none h-8 rounded-sm hover:bg-400/60 dark:hover:bg-slate-500 px-3 text-900";
  var className = path === to_ ? " " + baseStyle + " bg-400/60 dark:bg-slate-500 " : baseStyle;
  return React.createElement("button", {
              className: className,
              type: "button",
              onClick: (function (e) {
                  e.preventDefault();
                  RescriptReactRouter.push(to_);
                })
            }, children);
}

var make = NavLink;

export {
  make ,
}
/* react Not a pure module */
