// Generated by Melange

import * as React from "react";
import * as NavBar from "./components/NavBar.js";
import * as NotFound from "./pages/NotFound.js";
import * as ThemeHook from "./hooks/ThemeHook.js";
import * as ErrorBoundary from "./components/ErrorBoundary.js";
import * as SuspensionLoader from "./components/SuspensionLoader.js";
import * as RescriptReactRouter from "@rescript/react/./src/RescriptReactRouter.js";
import * as ThemeSwitchProvider from "./providers/ThemeSwitchProvider.js";

function App(Props) {
  var lazyHome = React.createElement(React.lazy(function (param) {
            var __x = import("./pages/Home.js");
            return __x.then(function (comp) {
                        return Promise.resolve({
                                    default: comp.make
                                  });
                      });
          }), undefined);
  var lazyAbout = React.createElement(React.lazy(function (param) {
            var __x = import("./pages/About.js");
            return __x.then(function (comp) {
                        return Promise.resolve({
                                    default: comp.make
                                  });
                      });
          }), undefined);
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var component = match ? (
      match.hd === "about" ? (
          match.tl ? React.createElement(NotFound.make, {}) : React.createElement(SuspensionLoader.make, {
                  children: lazyAbout
                })
        ) : React.createElement(NotFound.make, {})
    ) : React.createElement(SuspensionLoader.make, {
          children: lazyHome
        });
  var match$1 = ThemeHook.useTheme("theme-blue");
  return React.createElement(ThemeSwitchProvider.make, {
              value: match$1[1],
              children: React.createElement("div", {
                    className: "" + match$1[0] + " flex flex-col h-[100vh] dark:bg-slate-700 "
                  }, React.createElement(NavBar.make, {}), React.createElement(ErrorBoundary.make, {
                        children: React.createElement("div", {
                              className: "flex w-full h-full m-auto dark:bg-slate-700"
                            }, component)
                      }))
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
